# Generated by Django 5.2.14 on 2026-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('applies_to', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('both', 'Both')], default='both', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('L', 'L'), ('pcs', 'pcs'), ('pack', 'pack')], default='kg', max_length=10)),
                ('min_level', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Sizzling Steaks', 'Sizzling Steaks'), ('Burger With Fries', 'Burger With Fries'), ('Appetizer', 'Appetizer'), ('Pasta', 'Pasta'), ('Grilled Rice Meals', 'Grilled Rice Meals'), ('Sizzling Javalog 99ers', 'Sizzling Javalog 99ers'), ('Sizzling Javalog Special', 'Sizzling Javalog Special'), ('Brewsko Special', 'Brewsko Special'), ('Wings With Fries', 'Wings With Fries'), ('The Ultimate Sisig', 'The Ultimate Sisig'), ('Pizza', 'Pizza'), ('Coffee', 'Coffee'), ('Blended Drinks', 'Blended Drinks'), ('Non-Coffee', 'Non-Coffee'), ('Milk Tea', 'Milk Tea'), ('Refreshing', 'Refreshing'), ('Hot Tea', 'Hot Tea'), ('Add Ons', 'Add Ons')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('has_serving_style', models.BooleanField(default=False)),
                ('has_size', models.BooleanField(default=False)),
                ('has_temperature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
